######################################################################
# Automatically generated by qmake (3.0) Sa. Dez. 5 11:04:05 2015
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

QT += gui widgets

# Input
FORMS += OBDCUMainWindow.ui
SOURCES += Main.cpp
